// Generated by Selenium IDE
package es.uma.informatica.sii.trazabilidad.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class crudTitulacionesIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  private static final String UNIDAD_PERSITENCIA = "AgendaPU";
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    BaseDeDatos.inicializar(UNIDAD_PERSITENCIA);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void testVerTitulacion() {
	  
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudTitulaciones.xhtml");
	   
	    try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
		}
	  
	    assert(driver.findElement(By.id("dt-products:0:nombre")).getText().equals("Ingenieria Salud"));

    
  }
  
  @Test
  public void testCrearTitulacion() {      
      driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
  	  
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	  driver.findElement(By.id("login:user")).click();
	  driver.findElement(By.id("login:user")).sendKeys("rafa");
	  driver.findElement(By.id("login:pass")).sendKeys("1");
	  driver.findElement(By.cssSelector(".ui-button-text")).click();
	  
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudTitulaciones.xhtml");
    
	    try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
		}
	  
      WebElement element = driver.findElement(By.id("barraSup:crearTitBtn"));
      element.click();
	    try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
		}
  	  
      
      driver.findElement(By.id("addFrm:nombre")).click();
      driver.findElement(By.id("addFrm:nombre")).sendKeys("Ingenieria Computadores");
      driver.findElement(By.id("addFrm:codigo")).sendKeys("25212");
      driver.findElement(By.id("addFrm:creditos")).sendKeys("240");
      driver.findElement(By.id("addFrm:SaveBtn")).click();

      try {
			Thread.sleep(5000);
		} catch (InterruptedException e) {
		}
      
      boolean t = false;
      List<WebElement> listSpn = driver.findElement(By.id("dt-products_data")).findElements(By.tagName("span"));
      for(WebElement x:listSpn) {
    	  if(x.getText().equals("Ingenieria Computadores")){
    		  t=true;
    		  break;
    	  }
      }
      assert(t==true);
      
  }
  
  @Test
  public void testModificarTitulacion() {
	  driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
  
	driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	driver.findElement(By.id("login:user")).click();
	driver.findElement(By.id("login:user")).sendKeys("rafa");
	driver.findElement(By.id("login:pass")).sendKeys("1");
	driver.findElement(By.cssSelector(".ui-button-text")).click();
	driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudTitulaciones.xhtml");

    try {
		Thread.sleep(3000);
	} catch (InterruptedException e) {
	}
    
	driver.findElement(By.id("dt-products:0:btnEditar")).click();
	
    try {
		Thread.sleep(3000);
	} catch (InterruptedException e) {
	}

    driver.findElement(By.id("modificarForm:nombre")).clear();
    driver.findElement(By.id("modificarForm:nombre")).sendKeys("Ing Inf 2");
    
		
    driver.findElement(By.id("modificarForm:SaveBtn")).click();
    
    try {
		Thread.sleep(3000);
	} catch (InterruptedException e) {
	}

    assert(driver.findElement(By.id("dt-products:0:nombre")).getText().equals("Ing Inf 2"));

    
  }
  
  @Test
  public void testEliminarTitulacion() {
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudTitulaciones.xhtml");
	    
	    try {
			Thread.sleep(3000);
		} catch (InterruptedException e) {
		}
	    
    driver.findElement(By.id("dt-products:0:eliminarBtn")).click();
    
    try {
		Thread.sleep(2000);
	} catch (InterruptedException e) {

	}
    
    List<WebElement> elements = driver.findElements(By.id("dt-products:1:nombre"));
    assert(elements.size() == 0);
    
    

  }
  
}

