// Generated by Selenium IDE
package es.uma.informatica.sii.trazabilidad.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class crudAlumnosIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSITENCIA = "AgendaPU";
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    BaseDeDatos.inicializar(UNIDAD_PERSITENCIA);
    
  }
  @After
  public void tearDown() {
    driver.quit();
 
  }
  
  @Test
  public void VerAlumno() {
	  
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudAlumnos.xhtml");
	    
	    
	    
	    assertThat(driver.findElement(By.id("dt-products:0:dninOutPut")).getText(), is("2589886"));
	    assertThat(driver.findElement(By.id("dt-products:0:nombreOutPut")).getText(), is("Manuel"));
	    assertThat(driver.findElement(By.id("dt-products:0:apellido1OutPut")).getText(), is("Escobar"));
	    assertThat(driver.findElement(By.id("dt-products:0:appelido2OutPut")).getText(), is("Garcia"));
	    assertThat(driver.findElement(By.id("dt-products:0:emailOutPut")).getText(), is("mescobar@gmail.com"));
	    assertThat(driver.findElement(By.id("dt-products:0:movilOutPut")).getText(), is("222"));
	    assertThat(driver.findElement(By.id("dt-products:0:direccionOutPut")).getText(), is("Calle larios"));
    
    
  }
  
  @Test
  public void modificarAlumno() {
	  
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudAlumnos.xhtml");

	driver.findElement(By.id("dt-products:0:modificarBtn")).click();
	
    WebDriverWait wait = new WebDriverWait(driver, 2);       //Tiempo de espera
    By direccion =By.id("modificarForm:direccion");					 //Tiempo de espera
    wait.until(ExpectedConditions.elementToBeClickable(direccion));      //Tiempo de espera
    
    
	driver.findElement(By.id("modificarForm:direccion")).clear();
    driver.findElement(By.id("modificarForm:direccion")).sendKeys("Calle carranza");

    driver.findElement(By.cssSelector("#modificarForm\\3AmodificarDialogBtn > .ui-button-text")).click();
    
    
    assertThat(driver.findElement(By.id("dt-products:0:direccionOutPut")).getText(), is("Calle carranza"));
    
    
  }
  

  
  
  @Test
  public void crearAlumno() {
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudAlumnos.xhtml");
	    
	
	    
    driver.findElement(By.id("j_idt6:crearBtnListener")).click();
    WebDriverWait wait = new WebDriverWait(driver, 2);       //Tiempo de espera
    By dniInput =By.id("crearAlumnoForm:dni");					 //Tiempo de espera
    wait.until(ExpectedConditions.elementToBeClickable(dniInput));      //Tiempo de espera
    
    driver.findElement(By.id("crearAlumnoForm:dni")).sendKeys("888");
    driver.findElement(By.id("crearAlumnoForm:Nombre")).sendKeys("joel");
    driver.findElement(By.id("crearAlumnoForm:Apellido1")).sendKeys("yusuke");
    driver.findElement(By.id("crearAlumnoForm:Apellido2")).sendKeys("saito");
    driver.findElement(By.id("crearAlumnoForm:email_personal")).sendKeys("uheu@gmail.com");
    driver.findElement(By.id("crearAlumnoForm:email_institucional")).sendKeys("hola@uma.es");
    driver.findElement(By.id("crearAlumnoForm:telefono")).sendKeys("77");
    driver.findElement(By.id("crearAlumnoForm:movil")).sendKeys("77");
    driver.findElement(By.id("crearAlumnoForm:direccion")).sendKeys("77");
    driver.findElement(By.id("crearAlumnoForm:provincia")).sendKeys("7");
    driver.findElement(By.id("crearAlumnoForm:localidad")).sendKeys("7");
    driver.findElement(By.id("crearAlumnoForm:CP")).sendKeys("287387");
    driver.findElement(By.id("crearAlumnoForm:saveBtn")).click();
  }
  
  @Test
  public void eliminarAlumno() {
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/crudAlumnos.xhtml");
	    
	
	    
    driver.findElement(By.id("dt-products:0:eliminarBtn")).click();
    
    
    List<WebElement> elements = driver.findElements(By.id("dt-products:0:dninOutPut"));
    assert(elements.size() == 0);
    
    

  }

  

}
