// Generated by Selenium IDE
package es.uma.informatica.sii.trazabilidad.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class ImportarCsvGrupoAsigIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  private static final String UNIDAD_PERSITENCIA = "AgendaPU";
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    BaseDeDatos.inicializar(UNIDAD_PERSITENCIA);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Requisitos({"RF01"})
  @Test
  public void testImportarCsv() {
	  PrintWriter out;
	  try {
		  out = new PrintWriter("/home/alumno/Escritorio/samplegr.csv");
		  out.println("Aplicacion secretaria;;LAS ASIGNATURAS Y GRUPOS DEBEN EXISTIR EN EL SISTEMA"); 
		  out.println("Ingenieros a lo bestia;;");
		  out.println("Referencia(Asignatura);Grupo;CursoActual"); 
		  out.println("1;1;2020/2021");
		  out.println("2;2;2020/2021");
		  out.println("1;2;2020/2021"); 
		  out.println("3;2;2020/2021");
		  out.close();
	} catch (FileNotFoundException e) {

	}

	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
	    driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("rafa");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/vistaSecretaria.xhtml");
	    
	    try {
				Thread.sleep(6000);
			} catch (InterruptedException e) {
			}
      WebElement element = driver.findElement(By.id("frmUpload2:uplInput2_input"));
      element.sendKeys("/home/alumno/Escritorio/samplegr.csv");
      
      try {
		Thread.sleep(3000);
      } catch (InterruptedException e) {
      }
      
      List<WebElement> listBtn = driver.findElements(By.tagName("button"));
      for(WebElement w:listBtn) {
    	  String s = w.getAttribute("disabled");
    	  if(s == null) {
        	  if(w.getText().equals("Upload")){
        		  w.click();
        		  break;
        	  }
    	  }
      }
      
      try {
		Thread.sleep(3000);
      } catch (InterruptedException e) {
      }
      
      driver.findElement(By.id("barraSup:logout")).click();
      
      try {
		Thread.sleep(3000);
      } catch (InterruptedException e) {
      }
      
      driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/login.xhtml");
      
      try {
  			Thread.sleep(3000);
  		} catch (InterruptedException e) {
  		}
   
      driver.findElement(By.id("login:user")).click();
	    driver.findElement(By.id("login:user")).sendKeys("escobar");
	    driver.findElement(By.id("login:pass")).sendKeys("1");
	    driver.findElement(By.cssSelector(".ui-button-text")).click();
	    try {
  			Thread.sleep(3000);
  		} catch (InterruptedException e) {
  		}
	    
	  boolean f = false;
      List<WebElement> listSpn = driver.findElement(By.id("dt2_data")).findElements(By.tagName("td"));
      for(WebElement x:listSpn) {
    	  if(x.getText().equals("Calculo")){
    		  f=true;
    	  }
      }
      assert(f==true);
  }
}

