// Generated by Selenium IDE
package es.uma.informatica.sii.trazabilidad.tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InicioSesionIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static final String UNIDAD_PERSITENCIA = "AgendaPU";
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    BaseDeDatos.inicializar(UNIDAD_PERSITENCIA);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Requisitos({"RF14"})
  @Test
  public void inicioSesionIT() throws InterruptedException {
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("rafa");
    driver.findElement(By.id("login:pass")).sendKeys("1");
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/vistaSecretaria.xhtml");
    assertThat(driver.findElement(By.id("nombreSecretaria")).getText(), is("Rafael Flores"));
    driver.findElement(By.id("barraSup:logout")).click();
  
  }
  @Requisitos({"RF14"})
  @Test
  public void inicioSesionAlumno() throws InterruptedException {
	  driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/login.xhtml");
    driver.findElement(By.id("login:user")).click();
    driver.findElement(By.id("login:user")).sendKeys("escobar");
    driver.findElement(By.id("login:pass")).sendKeys("1");
    driver.findElement(By.id("login:j_idt10")).click();
    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/vistaAlumno.xhtml");
    
    assertThat(driver.findElement(By.id("barraArriba:nombrecompletoid")).getText(), is("Manuel Escobar Garcia"));
    driver.findElement(By.id("barraArriba:logoutId")).click();
    
    

  
  }
}
