// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
    driver.findElement(By.id("login:user")).sendKeys("rafa");
    driver.findElement(By.id("login:pass")).sendKeys("1");
    driver.findElement(By.cssSelector("#j_idt45 > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#j_idt6\\3Aj_idt24 > .ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#j_idt6\\3Aj_idt24 > .ui-button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("j_idt53:dni")).sendKeys("1234");
    driver.findElement(By.id("j_idt53:Nombre")).sendKeys("Joel");
    driver.findElement(By.id("j_idt53:Apellido1")).sendKeys("yusuke");
    driver.findElement(By.id("j_idt53:Apellido2")).sendKeys("saito");
    driver.findElement(By.id("j_idt53:email_personal")).sendKeys("duhue@gmail.com");
    driver.findElement(By.id("j_idt53:email_institucional")).sendKeys("hoola@uma.es");
    driver.findElement(By.id("j_idt53:telefono")).sendKeys("38e837");
    driver.findElement(By.id("j_idt53:movil")).sendKeys("8787");
    driver.findElement(By.id("j_idt53:direccion")).sendKeys("limonar");
    driver.findElement(By.id("j_idt53:provincia")).sendKeys("malaga");
    driver.findElement(By.id("j_idt53:localidad")).sendKeys("malaga");
    driver.findElement(By.id("j_idt53:CP")).sendKeys("29016");
    driver.findElement(By.name("j_idt53:j_idt67")).click();
    driver.findElement(By.cssSelector(".ui-button-text")).click();
  }
}
