// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UntitledTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("http://0.0.0.0:8080/trazabilidad-war/faces/loginAdmin.xhtml");
    driver.findElement(By.id("login:user")).sendKeys("rafa");
    driver.findElement(By.id("login:pass")).sendKeys("1");
    driver.findElement(By.cssSelector("#accessAlumnosBtn > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#j_idt6\\3A crearBtnListener > .ui-button-text")).click();
    driver.findElement(By.id("crearAlumnoForm:dni")).sendKeys("888");
    driver.findElement(By.id("crearAlumnoForm:Nombre")).sendKeys("joel");
    driver.findElement(By.id("crearAlumnoForm:Apellido1")).sendKeys("yusuke");
    driver.findElement(By.id("crearAlumnoForm:Apellido2")).sendKeys("saito");
    driver.findElement(By.id("crearAlumnoForm:email_personal")).sendKeys("uheu@gmail.com");
    driver.findElement(By.id("crearAlumnoForm:email_institucional")).sendKeys("hola@uma.es");
    driver.findElement(By.id("crearAlumnoForm:telefono")).sendKeys("77");
    driver.findElement(By.id("crearAlumnoForm:movil")).sendKeys("77");
    driver.findElement(By.id("crearAlumnoForm:direccion")).sendKeys("77");
    driver.findElement(By.id("crearAlumnoForm:provincia")).sendKeys("7");
    driver.findElement(By.id("crearAlumnoForm:localidad")).sendKeys("7");
    driver.findElement(By.id("crearAlumnoForm:CP")).sendKeys("287387");
    driver.findElement(By.id("crearAlumnoForm:saveBtn")).click();
  }
}
